AWSTemplateFormatVersion: '2010-09-09'
Description: 'Genomic Variant Analysis - Unified Studio Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: genomics-variant-analysis
    Description: Name of the project

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  DataRetentionDays:
    Type: Number
    Default: 90
    Description: S3 data retention in days

  MonthlyBudgetLimit:
    Type: Number
    Default: 50
    MinValue: 10
    Description: Monthly budget alert threshold (USD)

Resources:
  # S3 Bucket for VCF and genomic data
  GenomicsDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-data-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldData
            Status: Enabled
            ExpirationInDays: !Ref DataRetentionDays
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket for analysis results
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-results-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldResults
            Status: Enabled
            ExpirationInDays: !Ref DataRetentionDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # IAM Role for analysis notebooks/Lambda
  AnalysisRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - lambda.amazonaws.com
                - batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # S3 Access Policy
  S3AccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-s3-policy-${Environment}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DataBucketAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt GenomicsDataBucket.Arn
              - !Sub '${GenomicsDataBucket.Arn}/*'
          - Sid: ResultsBucketAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt ResultsBucket.Arn
              - !Sub '${ResultsBucket.Arn}/*'
          - Sid: PublicGenomicsData
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::1000genomes/*
              - arn:aws:s3:::1000genomes
              - arn:aws:s3:::gnomad-public-us-east-1/*
              - arn:aws:s3:::gnomad-public-us-east-1
      Roles:
        - !Ref AnalysisRole

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/${Environment}'
      RetentionInDays: 30

  # SNS Topic for alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alerts-${Environment}'
      DisplayName: Genomics Analysis Alerts
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # CloudWatch Alarm for S3 costs
  S3CostAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-s3-cost-${Environment}'
      AlarmDescription: Alert when S3 costs exceed threshold
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: !Ref MonthlyBudgetLimit
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: ServiceName
          Value: AmazonS3

Outputs:
  DataBucketName:
    Description: S3 bucket for genomic data
    Value: !Ref GenomicsDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  ResultsBucketName:
    Description: S3 bucket for analysis results
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucket'

  AnalysisRoleArn:
    Description: IAM role ARN for analysis
    Value: !GetAtt AnalysisRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  LogGroupName:
    Description: CloudWatch log group
    Value: !Ref LogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'

  AlertTopicArn:
    Description: SNS topic for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-AlertTopic'

  QuickStartGuide:
    Description: Getting started
    Value: !Sub |
      1. Configure AWS credentials
      2. Export environment variables:
         export DATA_BUCKET=${GenomicsDataBucket}
         export RESULTS_BUCKET=${ResultsBucket}
         export ROLE_ARN=${AnalysisRole.Arn}
      3. Install: pip install -e unified-studio/
      4. Upload VCF files to S3 data bucket
      5. Run analysis notebooks
