AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for Climate Model Ensemble Analysis in SageMaker Unified Studio'

Parameters:
  ProjectName:
    Type: String
    Default: climate-ensemble-analysis
    Description: Project name for resource naming

  NotebookInstanceType:
    Type: String
    Default: ml.t3.xlarge
    Description: SageMaker notebook instance type
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m5.xlarge
      - ml.m5.2xlarge

  VolumeSize:
    Type: Number
    Default: 50
    Description: EBS volume size in GB
    MinValue: 20
    MaxValue: 500

Resources:
  # S3 Bucket for Results
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-results-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: ClimateAnalysisResults

  # IAM Role for SageMaker
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-sagemaker-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Access to CMIP6 public dataset
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - 'arn:aws:s3:::cmip6-pds'
                  - 'arn:aws:s3:::cmip6-pds/*'
              # Access to results bucket
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt ResultsBucket.Arn
                  - !Sub '${ResultsBucket.Arn}/*'
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:InvokeModel'
                  - 'bedrock:InvokeModelWithResponseStream'
                  - 'bedrock:ListFoundationModels'
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/sagemaker/*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/sagemaker/${ProjectName}'
      RetentionInDays: 30

  # SNS Topic for Notifications (Optional)
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-notifications'
      DisplayName: Climate Analysis Notifications
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # CloudWatch Alarm for Cost Monitoring
  BudgetAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-cost-alert'
      AlarmDescription: Alert when estimated charges exceed threshold
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 86400  # 1 day
      EvaluationPeriods: 1
      Threshold: 50  # $50
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref NotificationTopic
      Dimensions:
        - Name: Currency
          Value: USD

Outputs:
  ResultsBucketName:
    Description: S3 bucket for analysis results
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucket'

  ResultsBucketArn:
    Description: ARN of results bucket
    Value: !GetAtt ResultsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucketArn'

  SageMakerRoleArn:
    Description: IAM role ARN for SageMaker
    Value: !GetAtt SageMakerExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SageMakerRole'

  NotificationTopicArn:
    Description: SNS topic for notifications
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  LogGroupName:
    Description: CloudWatch log group name
    Value: !Ref LogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'

  QuickStartCommand:
    Description: Command to get started
    Value: !Sub |
      # Deploy stack:
      aws cloudformation create-stack --stack-name ${ProjectName} --template-body file://climate-analysis-stack.yml --parameters file://parameters.json --capabilities CAPABILITY_NAMED_IAM

      # Check status:
      aws cloudformation describe-stacks --stack-name ${ProjectName} --query 'Stacks[0].StackStatus'

      # Get outputs:
      aws cloudformation describe-stacks --stack-name ${ProjectName} --query 'Stacks[0].Outputs'
