AWSTemplateFormatVersion: '2010-09-09'
Description: 'Brain Imaging Infrastructure - AWS Research Jumpstart'

Parameters:
  ProjectName:
    Type: String
    Default: brain-imaging
    Description: Project name for resource naming

  NotebookInstanceType:
    Type: String
    Default: ml.t3.xlarge
    AllowedValues:
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
    Description: SageMaker notebook instance type

  BatchComputeType:
    Type: String
    Default: SPOT
    AllowedValues:
      - EC2
      - SPOT
    Description: Use Spot instances for cost savings

  MaxvCpus:
    Type: Number
    Default: 256
    Description: Maximum vCPUs for Batch compute environment

Resources:
  # S3 Buckets
  BrainDataLake:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-data-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING

  ProcessingResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-results-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MLModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-models-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Glue Database
  NeuroimagingDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: neuroimaging_data
        Description: Neuroimaging metadata catalog

  # Glue Table - Subjects
  SubjectsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref NeuroimagingDatabase
      TableInput:
        Name: subjects
        Description: Subject-level metadata
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Columns:
            - Name: subject_id
              Type: string
            - Name: age
              Type: double
            - Name: sex
              Type: string
            - Name: diagnosis
              Type: string
            - Name: scanner_site
              Type: string
            - Name: dataset
              Type: string
          Location: !Sub 's3://${BrainDataLake}/metadata/subjects/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe

  # Glue Table - Scans
  ScansTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref NeuroimagingDatabase
      TableInput:
        Name: scans
        Description: Scan-level metadata
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Columns:
            - Name: subject_id
              Type: string
            - Name: session_id
              Type: string
            - Name: modality
              Type: string
            - Name: s3_path
              Type: string
            - Name: quality_rating
              Type: double
            - Name: processing_status
              Type: string
          Location: !Sub 's3://${BrainDataLake}/metadata/scans/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        PartitionKeys:
          - Name: dataset
            Type: string
          - Name: modality
            Type: string

  # Athena Workgroup
  NeuroimagingWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub '${ProjectName}-workgroup'
      Description: Workgroup for neuroimaging analysis
      WorkGroupConfiguration:
        ResultConfigurationUpdates:
          OutputLocation: !Sub 's3://${ProcessingResultsBucket}/athena-results/'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true

  # VPC for Batch (optional - can use default VPC)
  BatchVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

  BatchSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BatchVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-subnet'

  BatchInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'

  BatchVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BatchVPC
      InternetGatewayId: !Ref BatchInternetGateway

  BatchRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BatchVPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-rt'

  BatchRoute:
    Type: AWS::EC2::Route
    DependsOn: BatchVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref BatchRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BatchInternetGateway

  BatchSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BatchSubnet
      RouteTableId: !Ref BatchRouteTable

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Batch compute environment
      VpcId: !Ref BatchVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # IAM Role for Batch Jobs
  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-batch-job-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${BrainDataLake.Arn}/*'
                  - !GetAtt BrainDataLake.Arn
                  - !Sub '${ProcessingResultsBucket.Arn}/*'
                  - !GetAtt ProcessingResultsBucket.Arn
                  - !Sub '${MLModelsBucket.Arn}/*'
                  - !GetAtt MLModelsBucket.Arn

  # IAM Role for Batch Service
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-batch-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  # IAM Role for ECS Instance
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ecs-instance-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-ecs-instance-profile'
      Roles:
        - !Ref ECSInstanceRole

  # AWS Batch Compute Environment
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub '${ProjectName}-compute-env'
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: !Ref BatchComputeType
        MinvCpus: 0
        MaxvCpus: !Ref MaxvCpus
        DesiredvCpus: 0
        InstanceTypes:
          - c5
          - c5n
          - r5
          - r5n
        Subnets:
          - !Ref BatchSubnet
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        InstanceRole: !GetAtt ECSInstanceProfile.Arn

  # AWS Batch Job Queue
  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub '${ProjectName}-queue'
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment

  # Job Definition - FreeSurfer
  FreeSurferJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub '${ProjectName}-freesurfer'
      Type: container
      ContainerProperties:
        Image: freesurfer/freesurfer:7.3.2
        Vcpus: 4
        Memory: 16384
        JobRoleArn: !GetAtt BatchJobRole.Arn
        Command:
          - recon-all
          - -s
          - Ref::subject_id
          - -i
          - Ref::input_t1
          - -all
        MountPoints:
          - SourceVolume: data
            ContainerPath: /data
            ReadOnly: false
        Volumes:
          - Name: data
            Host:
              SourcePath: /mnt/efs

  # Job Definition - FSL Preprocessing
  FSLJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub '${ProjectName}-fsl'
      Type: container
      ContainerProperties:
        Image: brainlife/fsl:6.0.5
        Vcpus: 2
        Memory: 8192
        JobRoleArn: !GetAtt BatchJobRole.Arn
        Command:
          - /bin/bash
          - -c
          - Ref::fsl_command

  # IAM Role for SageMaker
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-sagemaker-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub '${BrainDataLake.Arn}/*'
                  - !GetAtt BrainDataLake.Arn
                  - !Sub '${ProcessingResultsBucket.Arn}/*'
                  - !GetAtt ProcessingResultsBucket.Arn
                  - !Sub '${MLModelsBucket.Arn}/*'
                  - !GetAtt MLModelsBucket.Arn
        - PolicyName: BatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - batch:SubmitJob
                  - batch:DescribeJobs
                  - batch:TerminateJob
                Resource: '*'

  # SageMaker Notebook
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Sub '${ProjectName}-notebook'
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      VolumeSizeInGB: 100
      DefaultCodeRepository: https://github.com/aws/research-jumpstart.git

Outputs:
  BrainDataLakeName:
    Description: S3 bucket for neuroimaging data
    Value: !Ref BrainDataLake
    Export:
      Name: !Sub '${AWS::StackName}-DataLake'

  ProcessingResultsBucketName:
    Description: S3 bucket for processing results
    Value: !Ref ProcessingResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucket'

  MLModelsBucketName:
    Description: S3 bucket for ML models
    Value: !Ref MLModelsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ModelsBucket'

  NeuroimagingDatabaseName:
    Description: Glue database for neuroimaging metadata
    Value: !Ref NeuroimagingDatabase

  BatchJobQueueArn:
    Description: AWS Batch job queue ARN
    Value: !Ref BatchJobQueue
    Export:
      Name: !Sub '${AWS::StackName}-JobQueue'

  FreeSurferJobDefinitionArn:
    Description: FreeSurfer job definition ARN
    Value: !Ref FreeSurferJobDefinition

  FSLJobDefinitionArn:
    Description: FSL job definition ARN
    Value: !Ref FSLJobDefinition

  SageMakerRoleArn:
    Description: IAM role for SageMaker execution
    Value: !GetAtt SageMakerExecutionRole.Arn

  NotebookInstanceName:
    Description: SageMaker notebook instance
    Value: !GetAtt NotebookInstance.NotebookInstanceName

  NotebookURL:
    Description: URL to access the notebook
    Value: !Sub 'https://${NotebookInstance.NotebookInstanceName}.notebook.${AWS::Region}.sagemaker.aws/lab'
