name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  python-lint:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          pip install -r .linting/requirements-lint.txt

      - name: Run Ruff
        run: ruff check --config .linting/ruff.toml .

      - name: Check formatting with Ruff
        run: ruff format --check --config .linting/ruff.toml .

      - name: Run mypy type checking
        run: mypy --config-file .linting/mypy.ini projects/ || true
        continue-on-error: true

      - name: Run Bandit security checks
        run: bandit -r projects/ -ll -i || true
        continue-on-error: true

      - name: Check for vulnerable dependencies
        run: safety check --json || true
        continue-on-error: true

  notebook-lint:
    name: Notebook Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install nbqa and linters
        run: |
          pip install nbqa ruff nbformat jupyter

      - name: Run nbqa with ruff on notebooks
        run: nbqa ruff projects/ --config .linting/ruff.toml || true
        continue-on-error: true

      - name: Validate notebook structure
        run: |
          find projects -name "*.ipynb" -not -path "*/.ipynb_checkpoints/*" | xargs -I {} python -m nbformat.validator {}
        continue-on-error: true

  cloudformation-lint:
    name: CloudFormation Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint
        run: cfn-lint --config-file .linting/.cfnlintrc.yaml projects/**/cloudformation/*.yml
        continue-on-error: true

  yaml-lint:
    name: YAML Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint -c .linting/.yamllint projects/**/cloudformation/*.yml
        continue-on-error: true

  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint --config .linting/.markdownlint.json '**/*.md' --ignore node_modules
        continue-on-error: true
