AWSTemplateFormatVersion: '2010-09-09'
Description: 'Social Media Analysis & Misinformation Detection - Unified Studio Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: social-media-analysis
    Description: Name of the project (used for resource naming)

  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  DataRetentionDays:
    Type: Number
    Default: 90
    MinValue: 1
    MaxValue: 3653
    Description: Number of days to retain data in S3 (1-3653)

  EnableComprehend:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable AWS Comprehend for advanced NLP analysis

  MonthlyBudgetLimit:
    Type: Number
    Default: 100
    MinValue: 10
    Description: Monthly budget limit in USD for cost alerts

Conditions:
  UseComprehend: !Equals [!Ref EnableComprehend, 'true']

Resources:
  # S3 Bucket for Social Media Data
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldData
            Status: Enabled
            ExpirationInDays: !Ref DataRetentionDays
            NoncurrentVersionExpirationInDays: 30
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # S3 Bucket for Results
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-results-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldResults
            Status: Enabled
            ExpirationInDays: !Ref DataRetentionDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for SageMaker/Analysis
  AnalysisRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-analysis-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # IAM Policy for S3 Access
  S3AccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-s3-access-${Environment}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DataBucketAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt DataBucket.Arn
              - !Sub '${DataBucket.Arn}/*'
          - Sid: ResultsBucketAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt ResultsBucket.Arn
              - !Sub '${ResultsBucket.Arn}/*'
          - Sid: PublicDataAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::*-public-datasets*
              - arn:aws:s3:::*-public-datasets*/*
      Roles:
        - !Ref AnalysisRole

  # IAM Policy for Comprehend (conditional)
  ComprehendPolicy:
    Type: AWS::IAM::Policy
    Condition: UseComprehend
    Properties:
      PolicyName: !Sub '${ProjectName}-comprehend-access-${Environment}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ComprehendAccess
            Effect: Allow
            Action:
              - comprehend:DetectSentiment
              - comprehend:DetectEntities
              - comprehend:DetectKeyPhrases
              - comprehend:DetectDominantLanguage
              - comprehend:DetectSyntax
              - comprehend:DetectPiiEntities
              - comprehend:BatchDetectSentiment
              - comprehend:BatchDetectEntities
              - comprehend:BatchDetectKeyPhrases
              - comprehend:BatchDetectDominantLanguage
            Resource: '*'
      Roles:
        - !Ref AnalysisRole

  # CloudWatch Log Group
  AnalysisLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/sagemaker/${ProjectName}-${Environment}'
      RetentionInDays: 30

  # SNS Topic for Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-alerts-${Environment}'
      DisplayName: Social Media Analysis Alerts
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Alarm for High Comprehend Costs
  ComprehendCostAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: UseComprehend
    Properties:
      AlarmName: !Sub '${ProjectName}-comprehend-cost-${Environment}'
      AlarmDescription: Alert when Comprehend costs exceed threshold
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 21600  # 6 hours
      EvaluationPeriods: 1
      Threshold: !Ref MonthlyBudgetLimit
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: ServiceName
          Value: AmazonComprehend

  # CloudWatch Alarm for High S3 Costs
  S3CostAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-s3-cost-${Environment}'
      AlarmDescription: Alert when S3 costs exceed threshold
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 21600  # 6 hours
      EvaluationPeriods: 1
      Threshold: 50  # $50 threshold
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      Dimensions:
        - Name: ServiceName
          Value: AmazonS3

Outputs:
  DataBucketName:
    Description: Name of the S3 bucket for social media data
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  ResultsBucketName:
    Description: Name of the S3 bucket for analysis results
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucket'

  AnalysisRoleArn:
    Description: ARN of the IAM role for analysis tasks
    Value: !GetAtt AnalysisRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  LogGroupName:
    Description: Name of the CloudWatch log group
    Value: !Ref AnalysisLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'

  AlertTopicArn:
    Description: ARN of the SNS topic for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${AWS::StackName}-AlertTopic'

  StackRegion:
    Description: AWS region where stack is deployed
    Value: !Ref AWS::Region

  # Cost Estimation Outputs
  EstimatedMonthlyCost:
    Description: Estimated monthly cost breakdown
    Value: !Sub |
      Base Infrastructure: ~$5-10/month (S3 storage, CloudWatch)
      Comprehend (if enabled): $0.0001/unit + $0.50/request (varies by usage)
      Data Transfer: Varies by volume
      Total: Highly dependent on data volume and API usage
      Budget Alert Set At: $${MonthlyBudgetLimit}/month

  # Quick Start Information
  QuickStartGuide:
    Description: Quick start instructions
    Value: !Sub |
      1. Configure AWS credentials with access to this stack
      2. Set environment variables:
         export DATA_BUCKET=${DataBucket}
         export RESULTS_BUCKET=${ResultsBucket}
         export ROLE_ARN=${AnalysisRole.Arn}
      3. Install Python package: pip install -e unified-studio/
      4. Run example notebook: jupyter lab unified-studio/notebooks/
      5. Monitor costs in CloudWatch and Billing Dashboard
