AWSTemplateFormatVersion: '2010-09-09'
Description: 'Precision Agriculture on AWS - Satellite data processing, IoT sensors, and ML yield prediction'

Parameters:
  ProjectName:
    Type: String
    Default: precision-agriculture
    Description: Project name for resource naming

  FarmName:
    Type: String
    Default: demo-farm
    Description: Farm name for organization

  SatelliteDataBucket:
    Type: String
    Default: sentinel-cogs
    Description: S3 bucket with satellite imagery (Sentinel-2 COGs)

Resources:
  # ============================================
  # S3 Buckets
  # ============================================

  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-raw-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldRawData
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-processed-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  ModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-models-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  PrescriptionMapsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-prescriptions-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # IoT Core
  # ============================================

  IoTTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: !Sub '${ProjectName}_sensor_data'
      TopicRulePayload:
        Description: Route sensor data to Timestream
        Sql: !Sub "SELECT * FROM 'farm/${FarmName}/sensors/+/data'"
        Actions:
          - Timestream:
              RoleArn: !GetAtt IoTTimestreamRole.Arn
              DatabaseName: !Ref TimestreamDatabase
              TableName: !Ref SensorDataTable
              Dimensions:
                - Name: farm_id
                  Value: ${FarmName}
                - Name: sensor_id
                  Value: ${topic(4)}

  IoTTimestreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonTimestreamFullAccess
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # Timestream Database
  # ============================================

  TimestreamDatabase:
    Type: AWS::Timestream::Database
    Properties:
      DatabaseName: !Sub '${ProjectName}_sensors'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  SensorDataTable:
    Type: AWS::Timestream::Table
    Properties:
      DatabaseName: !Ref TimestreamDatabase
      TableName: sensor_measurements
      RetentionProperties:
        MemoryStoreRetentionPeriodInHours: 24
        MagneticStoreRetentionPeriodInDays: 365
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # Glue Data Catalog
  # ============================================

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_catalog'
        Description: Data catalog for precision agriculture

  SatelliteDataTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: satellite_imagery
        StorageDescriptor:
          Location: !Sub 's3://${ProcessedDataBucket}/satellite/'
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
          Columns:
            - Name: date
              Type: string
            - Name: field_id
              Type: string
            - Name: ndvi_mean
              Type: double
            - Name: ndvi_std
              Type: double
            - Name: evi_mean
              Type: double
            - Name: cloud_cover
              Type: double
            - Name: s3_path
              Type: string
        PartitionKeys:
          - Name: year
            Type: string
          - Name: month
            Type: string

  # ============================================
  # Athena Workgroup
  # ============================================

  AthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub '${ProjectName}-workgroup'
      Description: Athena workgroup for agriculture analytics
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub 's3://${ProcessedDataBucket}/athena-results/'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # SageMaker Execution Role
  # ============================================

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt RawDataBucket.Arn
                  - !Sub '${RawDataBucket.Arn}/*'
                  - !GetAtt ProcessedDataBucket.Arn
                  - !Sub '${ProcessedDataBucket.Arn}/*'
                  - !GetAtt ModelsBucket.Arn
                  - !Sub '${ModelsBucket.Arn}/*'
        - PolicyName: TimestreamAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - timestream:DescribeEndpoints
                  - timestream:Select
                  - timestream:SelectValues
                Resource: '*'
              - Effect: Allow
                Action:
                  - timestream:Select
                  - timestream:SelectValues
                Resource:
                  - !GetAtt SensorDataTable.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ============================================
  # AWS Batch for Satellite Processing
  # ============================================

  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeEnvironmentName: !Sub '${ProjectName}-compute'
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: 256
        DesiredvCpus: 0
        InstanceTypes:
          - optimal
        InstanceRole: !GetAtt BatchInstanceProfile.Arn
        Subnets:
          - !Ref BatchSubnet
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
      State: ENABLED

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub '${ProjectName}-queue'
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      State: ENABLED

  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub '${ProjectName}-satellite-processing'
      Type: container
      ContainerProperties:
        Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}:latest'
        Vcpus: 4
        Memory: 16000
        JobRoleArn: !GetAtt BatchJobRole.Arn
        Environment:
          - Name: RAW_BUCKET
            Value: !Ref RawDataBucket
          - Name: PROCESSED_BUCKET
            Value: !Ref ProcessedDataBucket
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BatchInstanceRole

  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt RawDataBucket.Arn
                  - !Sub '${RawDataBucket.Arn}/*'
                  - !GetAtt ProcessedDataBucket.Arn
                  - !Sub '${ProcessedDataBucket.Arn}/*'
                  - !Sub 'arn:aws:s3:::${SatelliteDataBucket}'
                  - !Sub 'arn:aws:s3:::${SatelliteDataBucket}/*'

  # ============================================
  # VPC for Batch
  # ============================================

  BatchVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

  BatchSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BatchVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-subnet'

  BatchInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'

  BatchVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BatchVPC
      InternetGatewayId: !Ref BatchInternetGateway

  BatchRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BatchVPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-rt'

  BatchRoute:
    Type: AWS::EC2::Route
    DependsOn: BatchVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref BatchRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BatchInternetGateway

  BatchSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BatchSubnet
      RouteTableId: !Ref BatchRouteTable

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Batch compute environment
      VpcId: !Ref BatchVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # ============================================
  # Lambda for Scheduled Processing
  # ============================================

  SatelliteIngestionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-satellite-ingestion'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          RAW_BUCKET: !Ref RawDataBucket
          PROCESSED_BUCKET: !Ref ProcessedDataBucket
          FARM_NAME: !Ref FarmName
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from datetime import datetime, timedelta

          def lambda_handler(event, context):
              """
              Scheduled Lambda to check for new Sentinel-2 imagery
              and trigger Batch processing jobs
              """
              batch = boto3.client('batch')

              # Get farm boundaries from S3
              # Query Sentinel-2 for new imagery
              # Submit Batch jobs for processing

              return {
                  'statusCode': 200,
                  'body': json.dumps('Satellite ingestion completed')
              }

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt RawDataBucket.Arn
                  - !Sub '${RawDataBucket.Arn}/*'
                  - !GetAtt ProcessedDataBucket.Arn
                  - !Sub '${ProcessedDataBucket.Arn}/*'
        - PolicyName: BatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - batch:SubmitJob
                  - batch:DescribeJobs
                Resource: '*'

  ScheduledIngestionRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger satellite data ingestion daily
      ScheduleExpression: 'cron(0 6 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt SatelliteIngestionFunction.Arn
          Id: SatelliteIngestionTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SatelliteIngestionFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledIngestionRule.Arn

Outputs:
  RawDataBucket:
    Description: S3 bucket for raw satellite data
    Value: !Ref RawDataBucket

  ProcessedDataBucket:
    Description: S3 bucket for processed data
    Value: !Ref ProcessedDataBucket

  ModelsBucket:
    Description: S3 bucket for ML models
    Value: !Ref ModelsBucket

  PrescriptionMapsBucket:
    Description: S3 bucket for prescription maps
    Value: !Ref PrescriptionMapsBucket

  TimestreamDatabase:
    Description: Timestream database for sensor data
    Value: !Ref TimestreamDatabase

  SensorDataTable:
    Description: Timestream table for sensor measurements
    Value: !Ref SensorDataTable

  GlueDatabase:
    Description: Glue database for data catalog
    Value: !Ref GlueDatabase

  AthenaWorkgroup:
    Description: Athena workgroup for queries
    Value: !Ref AthenaWorkgroup

  SageMakerExecutionRole:
    Description: IAM role for SageMaker
    Value: !GetAtt SageMakerExecutionRole.Arn

  BatchJobQueue:
    Description: Batch job queue for satellite processing
    Value: !Ref BatchJobQueue
