AWSTemplateFormatVersion: '2010-09-09'
Description: 'Population Genetics Analysis Infrastructure - AWS Research Jumpstart'

Parameters:
  ProjectName:
    Type: String
    Default: population-genetics
    Description: Project name for resource naming

  NotebookInstanceType:
    Type: String
    Default: ml.t3.xlarge
    AllowedValues:
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m5.xlarge
      - ml.m5.2xlarge
    Description: SageMaker notebook instance type

Resources:
  # S3 Buckets
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-data-lake-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-results-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Glue Database
  GenomicsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_database'
        Description: 'Database for genomic variants and metadata'

  # Glue Table for Variants
  VariantsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GenomicsDatabase
      TableInput:
        Name: variants
        StorageDescriptor:
          Columns:
            - Name: chromosome
              Type: string
            - Name: position
              Type: bigint
            - Name: ref
              Type: string
            - Name: alt
              Type: string
            - Name: qual
              Type: double
            - Name: filter
              Type: string
            - Name: info
              Type: map<string,string>
            - Name: allele_frequency
              Type: double
            - Name: super_population
              Type: string
          Location: !Sub 's3://${DataLakeBucket}/variants/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
        PartitionKeys:
          - Name: chromosome
            Type: string
          - Name: super_population
            Type: string

  # Athena Workgroup
  GenomicsWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub '${ProjectName}-workgroup'
      Description: Workgroup for genomics queries
      WorkGroupConfiguration:
        ResultConfigurationUpdates:
          OutputLocation: !Sub 's3://${ResultsBucket}/athena-results/'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true

  # IAM Role for SageMaker
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-sagemaker-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${DataLakeBucket.Arn}/*'
                  - !GetAtt DataLakeBucket.Arn
                  - !Sub '${ResultsBucket.Arn}/*'
                  - !GetAtt ResultsBucket.Arn
                  - 'arn:aws:s3:::1000genomes/*'
        - PolicyName: AthenaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - athena:*
                  - glue:*
                Resource: '*'

  # SageMaker Notebook Instance
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Sub '${ProjectName}-notebook'
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !GetAtt SageMakerExecutionRole.Arn
      VolumeSizeInGB: 50
      DefaultCodeRepository: https://github.com/aws/research-jumpstart.git

Outputs:
  DataLakeBucketName:
    Description: S3 bucket for genomic data lake
    Value: !Ref DataLakeBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataLakeBucket'

  ResultsBucketName:
    Description: S3 bucket for analysis results
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucket'

  GlueDatabaseName:
    Description: Glue database for genomics
    Value: !Ref GenomicsDatabase
    Export:
      Name: !Sub '${AWS::StackName}-Database'

  AthenaWorkgroupName:
    Description: Athena workgroup for queries
    Value: !Ref GenomicsWorkgroup
    Export:
      Name: !Sub '${AWS::StackName}-Workgroup'

  NotebookInstanceName:
    Description: SageMaker notebook instance
    Value: !GetAtt NotebookInstance.NotebookInstanceName

  NotebookURL:
    Description: URL to access the notebook
    Value: !Sub 'https://${NotebookInstance.NotebookInstanceName}.notebook.${AWS::Region}.sagemaker.aws/lab'
